# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Message
version:      0.02
version_from: lib/Log/Message.pm
installdirs:  site
requires:
    File::Spec:                    0
    Locale::Maketext::Simple:      0
    Module::Load:                  0
    Params::Check:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
